### ISSUE TITLE
H5页面的header区域布局的学习（京东篇）

### ISSUE THREAD

**Issue by cy0707** [cy0707/hello-front-end#10]
### 后退键与标题和右边一个功能键的布局
![header_01](https://cloud.githubusercontent.com/assets/15865210/14978257/1d4d69b8-114d-11e6-83b0-7dab23ff12c6.jpg)
```html
<div id="m_common_header">
    <header class="jd-header">
        <div class="jd-header-bar">
            <div class="jd-header-icon-back">
               <span></span>
             </div>        
            <div class="jd-header-title">京东全球购</div>
            <div class="jd-header-icon-shortcut ">
               <span></span>
            </div>   
         </div>    
         <ul class="jd-header-shortcut" style="display: none"></ul>
    </header>
</div>
```
```css
#m_common_header {
    z-index: 11;
    position: relative;
}
/*这个是移动端的公共头部，用了相对定位和层级为11，
 *不过是用id来写的样式，最好能用class来代替
*/
.jd-header {
    min-height: 44px;
    padding: 0;
    margin: 0;
    text-decoration: none;
    color: #252525;
    width: 100%;
}
/*头部设置了最小高度为44px,这里是iOS状态栏的高度，无论在iphone4,5,6,6
 *状态栏的高度是不发生变化的。所以高度是固定的值。统一规定字体的颜色。
*/
.jd-header, .jd-header a {
    font-family: "PingHei","Lucida Grande", "Lucida Sans Unicode", "STHeiti",    "Helvetica","Arial","Verdana","sans-serif";
    color: #252525;
    text-decoration: none;
    font-size: 16px;
}
/*在这里，规定了统一的字体，字体大小，字体颜色，header跟在a标签一起写的做法
 *是因为a标签的字体只能在a标签里面写才生效，所以合在一起写,color和text-
decoration这两个属性重复了。
*/
.jd-header-bar {
    position: relative;
    background: #efefef url(../images/2015/header-bg.png?v=2) repeat-x 0 0;
    background-size: 100% 44px;
    min-height: 44px;
    border-bottom: 1px solid #bfbfbf;
    border-width: 0 0 1px 0;
}
/*对于headerbar的跟前面的m-commom-header类似，利用了sprite的图，平铺了背景，对于
 *border-bottom与border-width这两个同时写的做法，暂时还不太明白。记录一下。
*/
.jd-header-icon-back{
    position: absolute;
    width: 40px;
    height: 44px;
}
/*在返回按钮的图标外面套了一个div,直接写了，这个div的宽高，及点击区域大小
 *为40X44的区域，再以header-bar为基点，进行定位。
*/
.jd-header-icon-back span {
    width: 20px;
    height: 20px;
    background-position: -20px 0;
    margin: 12px 0 0 10px;
}
/*在这个返回区域的图标，直接写图标的大小，再以sprite图，定位出该图标
 *然后通过margin值，把图标调整到合适的位置。
*/
.jd-header-icon-back span, .jd-header-icon-shortcut span {
     display: block;
     background: url(../images/2015/jd-sprites.png?v=12) no-repeat;
     background-size: 200px 200px;
}
/*我们可以看见，京东的雪碧图是400X400，但是其background-size却是200X200
 *所以，这个图是两倍的图片，
 *border-bottom与border-width这两个同时写的做法，暂时还不太明白。记录一下。
*/
.jd-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
}
.jd-header-icon-shortcut, .jd-header-icon-category {
    position: absolute;
    right: 0;
    top: 0;
    width: 40px;
    height: 44px;
    overflow: hidden;
}
.jd-header-icon-shortcut span {
    width: 20px;
    height: 20px;
    background-position: -60px 0;
    margin: 12px 10px 0 10px;
}
.jd-header-icon-back span, .jd-header-icon-shortcut span {
    text-indent: -100px;
    overflow: hidden;
}
```
