### ISSUE TITLE
css中的定位理解

### ISSUE THREAD

**Issue by cy0707** [cy0707/hello-front-end#13]
## 非背景的定位
1.  fixed----固定定位(position:fixed 默认是相对浏览器窗口定位的)，下面会有其相对于父元素定位的例子
2.  relative----相对定位（是决定定位的参考点）
3.  absolute----绝对定位（以相对定位为参考点）

#### relative---相对定位的理解（直接利用看到一篇博文的理解）
```html
<div id="first"> first</div>  
<div id="second">second</div> 
```
未使用相对定位
![position-03](https://cloud.githubusercontent.com/assets/15865210/16832470/eb0d67a0-49dc-11e6-8a22-b863f7a3774b.jpg)
使用相对定位之后
![position-04](https://cloud.githubusercontent.com/assets/15865210/16832479/f2382394-49dc-11e6-9c14-dbfba5c0179a.jpg)

总结：相对定位相对的是它原本在文档流中的位置而进行的偏移，而我们也知道relative定位也是遵循正常的文档流，它没有脱离文档流，但是它的top/left/right/bottom属性是生效的，可以说它是static到absoult的一个中间过渡属性，最重要的是它还占有文档空间，而且占据的文档空间不会随 top / right / left / bottom 等属性的偏移而发生变动，也就是说它后面的元素是依据虚线位置( top / left / right / bottom 等属性生效之前)进行的定位，这点一定要理解。

#### absolut---绝对定位的理解（absoulte是根据祖先类的border进行的定位）
例如：当我们有一个100*100大小的里面的盒子以300*300的外面的盒子为定位点，是用固定的数字进行定位的话。里面绝对定位的盒子，是以外面的那个相对定位的左上角（0,0）为坐标原点进行定位的
```css
.container {
	position: relative;
	width: 300px;
	height: 300px;
	margin: 100px auto;
	background-color: #96c18e;
}
.box {
	position: absolute;
	left: 100px;
	top: 100px;
	width: 100px;
	height: 100px;
	background-color: #567b68;
}
```
```html
<div class="container">
	<div class="box">我是定位盒子</div>
</div>
```
![position-01](https://cloud.githubusercontent.com/assets/15865210/16831823/a11b9bd8-49d9-11e6-89cb-60a90e27673a.png)

当我们对定位的单位改为百分比时。绝对定位的left,top取决于相对定位的宽度*百分比。：
```css
.box {
	position: absolute;
	left: 80%;
	top: 80%;
	width: 100px;
	height: 100px;
	background-color: #567b68;
}
```
![position-02](https://cloud.githubusercontent.com/assets/15865210/16832003/bbeb4868-49da-11e6-846a-aa8e5f38c4a2.png)

当我们想实现一个盒子垂直居中的话

总结：absoulte定位，也称为绝对定位，虽然它的名字号曰“绝对”，但是它的功能却更接近于"相对"一词，为什么这么讲呢？原来，使用absoult定位的元素脱离文档流后，就只能根据祖先类元素(父类以上)进行定位，而这个祖先类还必须是以postion非static方式定位的， 举个例子，a元素使用absoulte定位，它会从父类开始找起，寻找以position非static方式定位的祖先类元素(注意，一定要是直系祖先才算哦~），直到<html>标签为止。
需要注意：relative和static方式在最外层时是以<body>标签为定位原点的，而absoulte方式在无父级是position非static定位时是以<html>作为原点定位。relative和static方式在最外层时是以<body>标签为定位原点的，而absoulte方式在无父级是position非static定位时是以<html>作为原点定位

#### left,right,top,bottom的理解

使用absoulte或fixed定位的话，必须指定 left、right、 top、 bottom 属性中的至少一个，否则left/right/top/bottom属性会使用它们的默认值 auto ，这将导致对象遵从正常的HTML布局规则，在前一个对象之后立即被呈递，简单讲就是都变成relative，会占用文档空间，这点非常重要，很多人使用absolute定位后发现没有脱离文档流就是这个原因少了left/right/top/bottom属性不行，那如果我们多设了呢？例如，我们同时设置了top和bottom的属性值，那元素又该往哪偏移好呢？
记住下面的规则：
 如果top和bottom一同存在的话，那么只有top生效。
 如果left和right一同存在的话，那么只有left生效。
