### ISSUE TITLE
layout的总结--第二部分

### ISSUE THREAD

**Issue by cy0707** [cy0707/hello-front-end#3]
*   图片自适应布局-----《精通css2.0》

例如，当你需要一个新闻列表样式，左边是窄的图片列，右边是比较大的文本列，图像的宽度大约是容器的四分之一，文本占剩下的空间。此时我们需要把图像的宽度设为25%；再设置其最大宽度为图像本身的尺寸，这样以防图片在高分辨率的电脑上面图像失真。
```html
<div class="news">
    <img src="..."  alt="新闻图片">
    <p>我是新闻的内容</p>
</div>
```
```css
.news img {
    float: left;
    width: 25%;
    max-width: 200px;
    padding: 2%;
}
.news p {
    float: right;
    width: 68%;
    padding: 2% 2% 2% 0;
}
```

*   创建3列高度相同的列-----《精通css2.0》
用表格布局容易实现这种布局，但是用css需要的一点技巧。
```html
<div class="wrapper">
    <div class="box">
        <h1>我是标题</h1>
        <p>我是文本段落...</p>
    </div>
    <div class="box">
        <h1>我是标题</h1>
        <p>我是文本段落...</p>
    </div>
    <div class="box">
        <h1>我是标题</h1>
        <p>我是文本段落...</p>
    </div>
</div>
```
对于这个布局，我们需要3个div，每个列一个class="box",在每一个div中，需要标题和一些内容，然后把这3个div放入容器wrapper的div中，限制高度。
```css
.wrapper {
    width: 100%;
    overflow: hidden;
}
.box {
    float: left;
    width: 250px;
    padding: 20px 20px 520px 20px;
    margin-bottom: -520px;
    margin-left: 20px;
}
```
对于wrapper容器用overflow: hidden的原因-----wrapper的高度是自动的，因为我们开始并没有明确的设置其高度，所以其高度由容器的内容，即容器的normal flow（普通流的内容）的高度来决定。这就是说容器的高度由里面内容普通流最后的位置决定。

![layout_col](https://cloud.githubusercontent.com/assets/15865210/13727979/fa942d4e-e942-11e5-99c2-9e909841a989.jpg)

其实这个原理是负margin的原理，margin-bottom 为负数的时候，是改变的这个元素的对下一个元素的参考线。但是这个元素本身的大小并没有变。变得只是对下一个元素的参考线。其意思是下一个元素，显示的位置，是padding-margin的的那条线。最后由于wrapper的overflow为hidden，所以对于三列div多余的内容被截取成一样高，但其实他们并不是一样高的。

总结：在普通流中，元素的最终边界由margin决定， margin为负的时候，就是相当于元素的边界向里收，普通流认得只是这个边界，而不管你的实际内容占得尺寸。

缺点:就是如果要实现每列四周有边框效果，那么每列的底部（或顶部）将无法有边框效果。此时的解决方法是（用背景图片---参考《精通css2.0》）：
分别在box盒子的div中加上一个空的<div class="buttom"></div>作为底边，为了把列的底边正确定位，需要把他们与容器元素的底部对齐。为此。
```css
.wrapper {
    positon: relative;
}
.buttom {
    position: absolute;
    left: 0;
    bottom: 0;
    width: 290px;
    height: 20px;
}
```
把buttom元素设置背景图片的需要的宽高。那这样就可以了。

*   三列等高布局-----假等高列（博主名字不知道）
这种方法是实现等高列最早使用的一种方法，就是使用背景图片，在列的父元素上使用这个背景图进行Y轴的铺放，从而实现一种等高列的假像：结构同上。
```css
.wrapper {
    background: url("...") repeat-y;
}
```
优点：
实现方法简单，兼容性强，不需要太多的css样式就可以轻松实现。

缺点：
使用这种方法不适合流体布局等高列的布局，另外如果你需要更换背景色或实现其他列数的等高列时，都需要重新制作过背景图。
