### ISSUE TITLE
负margin原理

### ISSUE THREAD

**Issue by cy0707** [cy0707/hello-front-end#4]
## 负margin的原理

![margin](https://cloud.githubusercontent.com/assets/15865210/13728410/348c0d6e-e952-11e5-84f6-eceb34b69e4e.jpg)

对于上图的理解，当我们给一个元素设置（left/top）方向的负margin值时，该元素将在该方向上面产生位移，当我们给一个元素设置（right/bottom）方向的负margin值时,该元素并不会向我们预想的那样，在这个方向上面产生位移，而是，将任何紧随其后的元素“拉”过来，覆盖在自己的上面。即就是下面那篇文章所说的参考线变化。

由浅入深漫谈margin属性 ----------来至 怿飞（http://www.planabc.net/about/）
读了这篇文章，我把几个重要的结论写下：

![margin_1](https://cloud.githubusercontent.com/assets/15865210/13728487/9b99403c-e955-11e5-860d-d2971f3fca47.png)

 top：以包含块的content上边或垂直上面相连元素margin下边为参考线，垂直下移。
 left：以包含块的content左边或者水平左边相连的元素margin的右边为参考线水平右位移。
 right：以元素本身的border右边为参考线水平右移。
 bottom：以元素本身的border下边为参考线垂直下移。

如果此时的margin为负值。那么上面的方向是刚好相反的。

根据CSS的定义，元素框的大小是由元素的margin、border、padding、width、height决定，再由上面的margin原理，通过测试得出。当margin-left为负数，以及margin-right为负数。会改变元素的实际大小和逻辑大小。margin-top与margin-bottom为负数改变的元素的逻辑大小，其实际大小并不会改变。这样就是说，水平方向的负值margin，会增加元素的宽度。同时改变其移动与参考线的位置，也就改变了其逻辑大小（按照上述负margin原理的规则）。但是在垂直方向的负值margin，并不会增加元素的高度，只会改变元素的移动与参考线的位置。
例如下面的例子（来至网友）
```html
<div id="test-width">No2父元素
    <p id="test-block">我是No2子元素 </p>
</div>
<div id="test-width2">No2父元素
    <p id="test-block2">我是No2子元素 </p>
</div>
```
```css
body{
    padding-top: 200px;
}
#test-width, #test-width2 {
    text-align: center;
    margin-right: auto;
    margin-left: auto;
    width: 400px;
    height: 80px;
    background-color: purple;
    float: left;
}
#test-width{
    background-color: yellow;
}
#test-block, #test-block2 {
    background-color: blue;
}
#test-block2 {
    margin-right: -100px;
    margin-left: -100px;
    background-color: red;
}
```
![margin_2](https://cloud.githubusercontent.com/assets/15865210/13728858/eb09543a-e960-11e5-827f-bc698ad1eda5.png)

从上面的图，我们可以看出。水平方向的宽度变大了，加上水平的负margin值。并且也向移动了。
参考线也改变了------看下面的例子。
```html
<div id="test-width">No2父元素
    <p id="test-block">我是No2子元素 </p>
</div>
<div id="test-width2">No2父元素
    <p id="test-block2">我是No2子元素 </p>
</div>
<div id="test-width">No2父元素
    <p id="test-block">我是No2子元素 </p>
</div>
```
我们可以与上图进行对比。我们就会元素发现大小变大了，并且向左移动100px以及参考线向左移动100px的变化。宽度变为400px+100px+100px=600px;
（下面的计算公式来至知乎---吕贤杰）
实际宽度（计算后的值） = width（本身宽度） + padding + margin
所以
width（本身宽度） = 实际宽度（计算后的宽度） - margin - padding
如果处于文本流中的元素没有设定宽度，它的实际宽度就是父元素的宽度，那么当margin为负，width值会比实际宽度值大 

http://www.planabc.net/2007/03/18/css_attribute_margin/
对于负margin的理解，感谢怿飞的文章。
