### ISSUE TITLE
包含块以及宽度和高度计算的理解

### ISSUE THREAD

**Issue by cy0707** [cy0707/hello-front-end#5]
## 包含块以及宽度和高度计算的理解
读了下面这篇文章css2.0标准的中文翻译文章，对于包含块有了一定的理解。现在把我的理解记录如下（下面是文章的链接）
http://www.css88.com/book/css2/visudet.html

####  包含块：
1.  定义
   一个元素的框的尺寸和位置的计算有时相对于某个特定的长方形，称为该元素的包含块。一个元素的包含块的定义如下：
    *  根元素存在的包含块（初始包含块）由用户端选择。 
    *  对于其它元素，它的包含块由它的最近的块类前辈框创建，除非它是绝对定位的。 
    *  如果元素设置了'position: fixed'，包含块由视点创建。 
    *  如果元素设置了'position: absolute'，包含块由最近的前辈创建（它的'position'不是'static'），方法如下： 
     * 如果前辈是块类元素，包含块由前辈的边白边形成。 
     * 如果前辈是行内元素，包含块取决于前辈的'direction'属性： 
        * 如果'direction'为'ltr'，包含块的顶、左边是该前辈创建的第一个框的顶、左内容边，它的底、右边是该前辈创建的最后一个框的底、右内容边。 
        * 如果'direction'为'rtl'，包含块的顶、右边是该前辈创建的第一个框的顶、右内容边，它的底、左边是该前辈创建的最后一个框的底、左内容边。 
    如果不存在这样的前辈，根元素框的内容边创建该包含块。 

例如：不考虑定位，下面文档的包含块（C.B.）
```html
<body>
    <div>
        <p class="one">hello world</p>
        <p class="teo">hello world<em>this is <strong> a nice</strong></em> </p>
</body>
```
此时的包含块的关系如下：

产生框的元素 | 创建C.B的元素
------------ | -------------
body | 初始C.B与（与用户端有关）
div | body
one | div
two | div
em | two
strong | two

如果，我们把div以及em的定位改变如下的话:
```css
div {
    position: absolute;
    left: 50px;
    top: 50px;
}
em {
    position: absolute;
    left: 150px;
    top: 15px;
}
```
那么包含块的关系就变成以下这样：

产生框的元素 | 创建C.B的元素
------------ | -------------
body | 初始C.B与（与用户端有关）
div | 初始C.B与（与用户端有关）
one | div
two | div
em | div
strong | em

因为div定位后，其最近前辈是body，但是body的position是static，所以是初始包含块，对于em定位后
最近的前辈元素position不为static的是div所以是div，对于strong其包含块是由最近的块类的前辈框创建
因为em定位了，所以成为了块框，所以其包含块是em 。

####  内容的宽度：width属性

属性 | 属性值的计算
------------ | -------------
值 | <length>  <percentage>  auto  inherit
初始值 | auto
适用于 | 所有元素，除了行内非替换元素，表格行和行组。
可否继承 | 否
百分比 | 基于包含块的宽度
媒介 | 图形

*   该属性指定了块类元素和替换元素产生的框的内容宽度。
*   该元素并不适用于非替换的行内元素。非替换行内元素框的宽度是它们中内容渲染后（在任何子元素相对偏移之前）的宽度。我们应该记得行内框排列在线框内。而线框的宽度由它们的包含块给出，但是可能由于出现浮动而被缩短。
*  替换元素的宽度是内在的，并且如果该属性值不是'auto'，用户端可能将其重新定比。
*   属性值的含义如下：
    *  <length>   指定一个固定宽度。 
    *  <percentage>   指定一个百分比宽度。百分比的计算基于生成框的包含块的宽度。 
    *  auto   宽度取决于其它属性的值 
    *  负的'width'值是非法的。

#### 宽度和边距的计算：
一个元素的'width'，'margin-left'，'margin-right'，'left'和'right'属性的计算值取决于产生的框的类型，并互相影响。一般而言，计算值和指定值相同，'auto'被某个合适的值取代。不过还是有例外。下面这些情况需要加以考虑：
*   行内的非替换元素
*   行内的替换元素
*   常规流向中的块类、非替换元素
*   常规流向中的块类、替换元素
*   浮动的非替换元素
*   浮动的替换元素
*   绝对定位的非替换元素
*   绝对定位的替换元素 
*   1-6包括相对定位

下面对上面得特殊情况进行分析：
1）行内的非替换元素：width属性不适用。对'padding-left'，'padding-right'，'margin-left'或'margin-right'指定'auto'的效果是计算值为'0'。 
例如：
```html
<p>hello<span>world></span></p>
```
```css
 p {
    background-color: #212b35;
    color: #fff;
    line-height: 50px;
 }
 span {
    width: 600px;
    background-color: #f7b42a;
    margin-left: auto;
    margin-right: auto;
 }
```
我们可以宽度并没有生效，margin-left与margin-right设置为auto时，也没有任何变化，其实被解析
为0；
![cb_1](https://cloud.githubusercontent.com/assets/15865210/13772930/ba06161c-ead1-11e5-9e21-12821d406e22.jpg)

2）行内的替换元素：宽度是生效的，对'padding-left'，'padding-right'，'margin-left'或'margin-right'指定'auto'的效果是计算值为'0'。指定'width'为'auto'将元素的内在宽度（就是浏览器开始设置的宽度）赋给计算值。 
 
```html
<p>hello<input class="one"></p>
<p>hello<input class="two"></p>
```
```css
 p {
    background-color: #212b35;
    color: #fff;
    line-height: 50px;
 }
.one{
    margin-left: 20px;
    margin-right: 20px;
 }
 .two{
    width: 600px;
    margin-left: auto;
    margin-right: auto;
}
```
![cb_2](https://cloud.githubusercontent.com/assets/15865210/13773267/619e4006-ead3-11e5-9c06-0800377a1124.jpg)

3）常规流向中的块类、非替换元素：
  *  如果'padding-left'或'padding-right'设置为'auto'，它们的计算值为0。在其它属性间必须保持下面的约束： 'margin-left' + 'border-left-width' + 'padding-left' + 'width' + 'padding-right' + 'border-right-width' +  'margin-right' = 包含块的宽度 
  *  （如果边框的样式为'none'，边框宽度认为是'0'。）
  *  如果上述所有的属性指定了非'auto'的值，这些值被称为是“过度约束”，其中之一的计算值将不
     得不 和它的指定值不同。
  *  如果'direction'属性为'ltr'，'margin-right'的指定值被忽略，并重新计算以满足上面的等式。如果'direction'为'rtl'，对'margin-left'采取上述的方法。
  *  如果只有一个值指定为'auto'，它的计算值从等式中得出。
  *  如果'width'设置为'auto'，则其它的'auto'值成为'0'而'width'从等式的剩余部分得到。
  *  如果'margin-left'和'margin-right'为'auto'，它们的计算值相同。
```html
<p class="one">hello</p>
<p class="two">hello</p>
```
```css
body {
   background-color: #00a2d8;
}
p { 
    color: #fff;
    line-height: 50px;       
 }
.one {
   background-color: #212b35; 
   padding-left: auto;
   padding-right: auto;
}
.two {
    background-color: #f9b72a;
    padding-left: 20px;
    padding-right: 20px;
 }
```

![cb_3](https://cloud.githubusercontent.com/assets/15865210/13774271/1a66f4de-ead9-11e5-8d1e-4b12b4f4a716.jpg)

对上面的3-7条并不是理解（记着，等以后会了，再说）

4）常规流向中的块类、替换元素：
如果'padding-left'或'padding-right'为'auto'，它们的计算值为0。如果'width'指定为'auto'，它的值是元素的内在宽度（浏览器规定的宽度）。如果某一个边距设置为'auto'，它的计算值由上述的约束给出。更进一步，如果两个边距都设置了'auto'，它们的计算值相等。 
这个类似于行内替换元素

5）浮动的非替换元素：
如果'padding-left'，'padding-right'，'width'，'margin-left'或'margin-right'指定为'auto'，它们的计算值为'0'。 (对于其中的宽度，当里面有内容的时候，其宽度设置为auto时，其宽度由内容撑开）
```html
<p class="one">hello</p>
<p class="two">hello</p>
<p class="three"></p>
```
```css
body {
   background-color: #00a2d8;
}
p{ 
    color: #fff;
    line-height: 50px;       
 }
.one {
   background-color: #212b35; 
   float: left;
   width: auto;
   margin-left: auto;
   margin-right: auto;
   padding-left: auto;
   padding-right: auto;
}
.two {
    background-color: #f9b72a;
    padding-left: 20px;
    margin-left: 20px;
 }
 .three {
    background-color: #fff;
 }
```
![cb_5](https://cloud.githubusercontent.com/assets/15865210/13775081/8cbb34d8-eadd-11e5-9629-40c176af5415.jpg)

 6）浮动的替换元素：
如果'left'，'right'，'margin-left'或'margin-right'指定为'auto'，它们的计算值为'0'。如果'width'为 'auto'，它的值是元素的内在宽度。 （类似行内替换元素）

7）绝对定位的非替换元素：
 *  这些元素计算值的约束为：'left' + 'margin-left' + 'border-left-width' + 'padding-left' + 'width' + 'padding-right' + 'border-right-width' + 'margin-right' + 'right' = 包含块的宽度 
 *  （如果边框样式为'none'，边框宽度认为是'0'。这一约束的实现通过如下顺序的一系列替换而达到：
 *   如果'left'设置为'auto'而'direction'为'ltr'，替换'auto'为：包含块左边到假定它的'position'属性设置为 'static'，而生成元素的第一个框的那个假想框的左边距边的距离。（但是为了不去实际计算那个框，用户端可以自由地猜想它可能在的位置。）如果假想框在包含块的左边，该值为负数。
 *  如果'right'设置为'auto'而'direction'为'rtl'，替换'auto'为：包含块右边到上述提到的那个假想框的右边距边的距离。如果假想框在包含块边的左边，该值为正数。
 *  如果'width'为'auto'，将剩余'left'或'right'的'auto'替换为'0'。
 *  如果'left'，'right'或'width'还是'auto'，将所有'margin-left'或'margin-right'的'auto'替换为'0'。
 *  如果在这一步'margin-left'和'margin-right'还是'auto'，基于额外的约束即两个边距必须相同，解出等式。
 *  如果在这一步只有一个'auto'存在，根据等式解出那个值。
 *  如果在这一步各值间过度约束，要么忽略'left'的值（如果'direction'为'rtl'），要么忽略'right'的值（如果'direction'为'ltr'），然后解出那个值。 

8）绝对定位的替换元素：
*  这一情况和前一情形类似，但是元素有一个内在宽度。替换的顺序是：
*  如果'width'为'auto'，替换为元素的内在宽度。
*  如果'left'设置为'auto'而'direction'为'ltr'，替换'auto'为：包含块左边到假定它的'position'属性设置为'static'，而生成元素的第一个框的那个假想框的左边距边的距离。（但是为了不去实际计算那个框，用户端可以自由地猜想它可能在的位置。）如果假想框在包含块的左边，该值为负数。
*  如果'right'设置为'auto'而'direction'为'rtl'，替换'auto'为：包含块右边到上述提到的那个假想框的右边距边的距离。如果假想框在包含块边的左边，该值为正数。
*  如果'left'或'right'是'auto'，将所有'margin-left'或'margin-right'的'auto'替换为'0'。
*  如果在这一步'margin-left'和'margin-right'还是'auto'，基于额外的约束即两个边距必须相同，解出等式。
*  如果在这一步只有一个'auto'存在，根据等式解出那个值。
*  如果在这一步各值间过度约束，要么忽略'left'的值（如果'direction'为'rtl'），要么忽略'right'的值（如果'direction'为'ltr'），然后解出那个值。 

对于绝对定位的计算规则不是很理解（留着，懂了再说）
