### ISSUE TITLE
替换元素以及非替换预算和行高的理解

### ISSUE THREAD

**Issue by cy0707** [cy0707/hello-front-end#6]
## 替换元素以及非替换预算和行高的理解
感谢下面博文的分享。对我的很有帮助。读了下面的博文谈谈我的理解吧。

1）替换元素：替换元素是浏览器根据其标签的元素与属性来判断显示具体的内容。img、input、textarea、select、object 等都是替换元素，这些元素都没有实际的内容。在某些情况下audio、canvas 也是替换元素。css在某些情况下，在计算替换元素的margin或者auto属性值的时候，有些特别。一些替换元素，但并不是全部，有内在尺寸或者基线的元素，可以用vertical-align属性。
2）非替换元素：出掉替换元素，剩下的都是非替换元素。大多数元素是不可替换元素，他们将内容直接告诉浏览器，将其显示出来。比如 p的内容，浏览器将把这段内容直接显示出来。
3）行高：
  *  对于块级元素，CSS属性line-height指定了元素内部line-boxes的最小高度。
  *  对于行内非替换元素，line-height用于计算line box的高度。
  *  对于行内替换元素，如button 或其他input元素，line-height没有影响（大多数浏览器并未有按照css的规范来）。
对上面的规则的解释：
*  对于块级元素
```html
<div>Lorem ipsum <span>hello</span>dolor sit amet </div>
<p>Lorem ipsum <span>hello</span>dolor sit amet </p>
```
```css
body {
  padding-top: 40px;
}
div {
  background-color: #7b9ab5;
}
p {
  padding: 20px;
  margin: 20px;
  line-height: 40px;
  background-color: #d9ab2b;
}
```
![l_h_1](https://cloud.githubusercontent.com/assets/15865210/13807958/ce44fd00-eb9e-11e5-9081-4f1106e96bee.png)

*  对于行内非替换元素与行内替换元素的计算比较
```html
<div>Lorem ipsum <span>hello</span>dolor sit amet </div>
<p>Lorem ipsum dolor <input type="text"> adipisicing elit. Ratione, laboriosam.</p>
<p>Lorem ipsum dolor <span>hello</span> adipisicing elit. Ratione, laboriosam.</p>
```
```css
body {
  padding-top: 40px;
}
div {
  background-color: #7b9ab5;
}
p {
  line-height: 40px;
  background-color: #d9ab2b;
}
span {
  padding: 40px;
  margin: 40px;
  background-color: #e8e6df;	
}
input {
  padding: 40px;
  margin: 40px;
  background-color: #e36a6c;
}
p span {
	line-height: 40px;
	padding: 0;
	margin: 0;
	background-color: #7b9ab5;
}
```
![l_h_4](https://cloud.githubusercontent.com/assets/15865210/13808051/2c9d31c4-eb9f-11e5-9603-eb2169d27ab1.png)

http://www.cnblogs.com/fengzheng126/archive/2012/05/18/2507632.html
https://segmentfault.com/a/1190000003038583
https://developer.mozilla.org/zh-CN/docs/Web/CSS/line-height
https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element
